### PR TITLE
Return proposals during training to allow evaluation.

### PR DESCRIPTION
**Pull request by hadim**
It allows performing evaluation during training.

### CODE REVIEW

**Comment by fmassa** [comment]
We can use `not self.training` for evaluation.

I think that having a separate process (potentially in a separate machine) is maybe more desirable. This was something that has been asked already, and the original Detectron has such functionality, so I think it might be a good thing to follow.

**Comment by hadim** [comment]
Ok, no problem. Everyone can have a custom training loop anyway.

But in that case, are you suggest to have a new `model` object used only for evaluation?

**Comment by fmassa** [comment]
If you want to use some model for evaluation, just put it in `model.eval()` mode before starting the evaluation, and move it back to `model.train()` mode just before the training.

Another possibility would be to enable to have some hooks that can be attached to the training job, and that could enable the evaluation to be performed at every x iterations.
But care should be taken when using multiple GPUs with distributed data parallel (like unwrapping the `DistributedDataParallel` model for inference, and wrapping it back for training).

**Comment by hadim** [comment]
Ok I see. I'll use `model.train()` and `model.eval()` then. Thank you. I'll close here.

**Comment by fmassa** [comment]
Thanks for the PRs and the contributions!

**Pull request closed without merging**
