### PR TITLE
Update test_net.py, checkpoint.py to support "--load-pth"

### PR DESCRIPTION
**Pull request by DIYer22**
Split `Checkpointer.load` to support choice which .pth file to load for test

### CODE REVIEW

**Comment by fmassa** [comment]
Thanks for the PR!
Could you just expand a bit on why this is needed?

**Comment by DIYer22** [comment]
According to [this line](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/utils/checkpoint.py#L54)

If os.path.isfile("OUTPUT_DIR/last_checkpoint"), MODEL.WEIGHT will be override by "OUTPUT_DIR/last_checkpoint"

When user what to test another .pth file(MODEL.WEIGHT), the loaded weights will be  "OUTPUT_DIR/last_checkpoint", rather than MODEL.WEIGHT

**Comment by fmassa** [comment]
Yes, but if you change `OUTPUT_DIR` to point to a different path (which you might want to do to avoid overwriting data in the current training folder), then the problem disappears, right?

**Comment by DIYer22** [comment]
😂, It's seens  that no document to suggest user to change `OUTPUT_DIR` when test. 
I think there is some users have the same problem like I got, because those users may put a experment(include train and test) into one `OUTPUT_DIR`  in commonsense.

**Comment by fmassa** [comment]
I meant that if you test on the same folder as when training, it will create a new subfolder with the results of the experiments using the latest checkpoint.
But if you just re-run it again with your patch, I believe it will overwrite the results from this subfolder, as it will have the same name for the files, right?

It might be a good idea to mention a possible solution in the README or something, what do you think?

**Comment by DIYer22** [comment]
I think so, it's better to mention user that to change OUTPUT_DIR when want to test on  specific .pth file(MODEL.WEIGHT).

**Comment by fmassa** [comment]
@DIYer22 would you be willing to send a PR improving the README? Thanks!

**Pull request closed without merging**
