### PR TITLE
let the saved predictions.pth make more sense

### PR DESCRIPTION
**Pull request by CoinCheung**
Maybe this will be helpful if we want to match the predictions with the associated image_ids.

### CODE REVIEW

**Comment by fmassa** [comment]
Hi,

While this makes sense, it makes it kind of incompatible with the Pascal dataset.

Also, the meaning of `predictions.pth` is now the same for both datasets: the index is wrt to index of the dataset, and this PR would change it to use the numeric indices from coco itself.

I think that documenting this behavior would be maybe better, and would avoid backward-incompatible files with the codebase?

**Comment by CoinCheung** [comment]
Thanks a lot for explaining. So after I have run my test script, how could I use the results to draw the predictions to my test set images?

**Comment by CoinCheung** [comment]
I am closing this since this is not the expected way to modify the code :)

**Comment by fmassa** [comment]
Hi,

Sorry for the delay in replying.

> how could I use the results to draw the predictions to my test set images?

So, I would load the `predictions.pth` file and the `COCODataset` corresponding to it, and then we are able to get the mapping from indices to image ids

**Comment by CoinCheung** [comment]
Got it, I have try it. Thanks!!

**Pull request closed without merging**
