### PR TITLE
please set 'STRIDE_IN_1X1' to be 'False' when backbone uses GN

### PR DESCRIPTION
**Pull request by zimenglan-sysu-512**
to fix the performance gap compared to Detectron.

### CODE REVIEW

**Comment by fmassa** [comment]
Can I merge this now or do you want me to wait (maybe for some results to finish computing)?

**Comment by zimenglan-sysu-512** [comment]
hi @fmassa 
maybe wait for the trainings, because it will need 2 days to finish.

**Comment by fmassa** [comment]
Let's do it like the following: once the trainings are over, you can send another PR updating maybe the `MODEL_ZOO` description of the GN model that you trained?

**Comment by zimenglan-sysu-512** [comment]
ok.
agree with u

**Comment by clw5180** [comment]
> Let's do it like the following: once the trainings are over, you can send another PR updating maybe the `MODEL_ZOO` description of the GN model that you trained?

Hi fmassa, I have a question here: What does the STRIDE_IN_1X1 mean? If I use ResNeXt101-FPN, should I set this option to True? Thanks a lot ! @fmassa

**Pull request merged**
