### PR TITLE
Fix the AssertionError when calling masker in coco_eval.py

### PR DESCRIPTION
**Pull request by henrywang1**
After applying the changes in #207.
I got the same AssertionError as described in #185 when I executing
```console
python tools/test_net.py --config-file "configs/caffe2/e2e_mask_rcnn_R_50_FPN_1x_caffe2.yaml" TEST.IMS_PER_BATCH 2
```
It could be fixed by doing the same way as #187 .

### CODE REVIEW

**Comment by henrywang1** [comment]
The performance seems to become bad due to pass masks to Masker, so I decide to drop the PR currently.

**Comment by fmassa** [comment]
So the code is not working for you, is that right?

**Comment by henrywang1** [comment]
I got the AssertionError, so I made some [changes](https://github.com/facebookresearch/maskrcnn-benchmark/pull/213/files), and it worked.

But later, I found the performance drops when evaluating the results, so I decided to check it again and cancel the PR.

I think the below command could reproduce the error,
```console
python tools/test_net.py --config-file "configs/caffe2/e2e_mask_rcnn_R_50_FPN_1x_caffe2.yaml" TEST.IMS_PER_BATCH 2
```

**Comment by fmassa** [comment]
Also, can you tell me what is the AssertionError that you got, just to double check?

**Comment by henrywang1** [comment]
Hi @fmassa 
Thanks for your reply.
Here is the AssertionError.
```console
2018-11-26 19:46:20,913 maskrcnn_benchmark.inference INFO: Total inference time: 0:01:23.692130 (0.13390740776062013 s / img per device, on 8 devices)
2018-11-26 19:46:23,992 maskrcnn_benchmark.inference INFO: Preparing results for COCO format
2018-11-26 19:46:23,992 maskrcnn_benchmark.inference INFO: Preparing bbox results
2018-11-26 19:46:24,971 maskrcnn_benchmark.inference INFO: Preparing segm results
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "tools/test_net.py", line 94, in <module>
    main()
  File "tools/test_net.py", line 88, in main
    output_folder=output_folder,
  File "/home/henrywang/github/maskrcnn-benchmark/maskrcnn_benchmark/engine/inference.py", line 104, in inference
    **extra_args)
  File "/home/henrywang/github/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/__init__.py", line 22, in evaluate
    return coco_evaluation(**args)
  File "/home/henrywang/github/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/coco/__init__.py", line 20, in coco_evaluation
    expected_results_sigma_tol=expected_results_sigma_tol,
  File "/home/henrywang/github/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py", line 47, in do_coco_evaluation
    coco_results["segm"] = prepare_for_coco_segmentation(predictions, dataset)
  File "/home/henrywang/github/maskrcnn-benchmark/maskrcnn_benchmark/data/datasets/evaluation/coco/coco_eval.py", line 119, in prepare_for_coco_segmentation
    masks = masker(masks, prediction)
  File "/home/henrywang/github/maskrcnn-benchmark/maskrcnn_benchmark/modeling/roi_heads/mask_head/inference.py", line 185, in __call__
    assert len(boxes) == len(masks), "Masks and boxes should have the same length."
AssertionError: Masks and boxes should have the same length.

```

**Comment by henrywang1** [comment]
After checking it again, I decide to reopen the PR and wait for your review.
The performance is bad because I was testing on some large images. (2048*1024)
and it will make the Masker spending more time.
I just found there are some discussions about this before.

**Comment by fmassa** [comment]
Oh, I just realized where the problem is actually: when I rebased the Pascal commit, I forgot to add [this part of the code](https://github.com/facebookresearch/maskrcnn-benchmark/blob/7bc870848a61d862ef4e34b57b020708b10ab346/maskrcnn_benchmark/engine/inference.py#L93-L95).

Can you please update your PR with the aforementioned fix, and I'll merge this?

Thanks!

**Pull request merged**
