### PR TITLE
Fix dispatch breakage

### PR DESCRIPTION
**Pull request by vishwakftw**
@fmassa This fixes the dispatch breakage introduced by https://github.com/pytorch/pytorch/commit/3aeb78079bcd68282fe9117088e138b77318e288.

Closes https://github.com/pytorch/pytorch/issues/17861

### CODE REVIEW

**Comment by fmassa** [comment]
Thanks!

But I suppose that we need now to ask users to use PyTorch from source, or else it will break for those who are using PyTorch 1.0, or 1.0.1, right?

**Comment by vishwakftw** [comment]
The installation instructions suggested to use the nightly build, which is why I sent in a PR.

**Comment by fmassa** [comment]
That used to be the case, but we have since https://github.com/facebookresearch/maskrcnn-benchmark/pull/510 changed it to install from a pinned version.

Something should be changed, here are a few possibilities:
- change the install instructions to install from a nightly, and add a big warning there saying that this repo doesn't work with 1.0 or 1.0.1
- revert this patch and keep this repo only working on a pinned version of PyTorch
- find a better solution

**Comment by fmassa** [comment]
As it turns out, #510 had a bugged install anyway, so I'll be reverting parts of it, and in the meantime I'll also make it work only on a nightly version

**Comment by vishwakftw** [comment]
Oh I'm sorry I didn't see the installation snippet. The first line in [INSTALL.md](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/INSTALL.md) seems to be misleading.

**Comment by fmassa** [comment]
@vishwakftw I'll fix the installation instructions, don't worry, they are bugged now anyway :-D

**Comment by vishwakftw** [comment]
Thank you, and sorry about the confusion.

**Comment by fmassa** [comment]
No worries, thanks for fixing this issue so quickly!

**Comment by drcege** [comment]
> @vishwakftw I'll fix the installation instructions, don't worry, they are bugged now anyway :-D
 
The first line of Installation/Requirements (`PyTorch 1.0 from a nightly release`) is still misleading.
The nightly release is now `PyTorch 1.1` (am I right?).  And README also said the project is using PyTorch 1.0.

By the way, are Dockerfiles up to date?

**Pull request merged**
